"""add ZUPC to ADS

Revision ID: 4bf756d958a1
Revises: 33fce94e17af
Create Date: 2015-04-01 10:22:40.293872

"""

# revision identifiers, used by Alembic.
revision = '4bf756d958a1'
down_revision = '33fce94e17af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ADS', sa.Column('ZUPC_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ADS', 'ZUPC', ['ZUPC_id'], ['id'])
    op.alter_column('departement', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departement', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'ADS', type_='foreignkey')
    op.drop_column('ADS', 'ZUPC_id')
    ### end Alembic commands ###
