"""Add customer model

Revision ID: 3c69c378bdb9
Revises: fd02d1c7d64
Create Date: 2015-04-15 18:07:49.918020

"""

# revision identifiers, used by Alembic.
revision = '3c69c378bdb9'
down_revision = 'fd02d1c7d64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('nb_sanctions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'operateur_id')
    )
    op.add_column('hail', sa.Column('customer_id', sa.String(), nullable=False))
    op.add_column('hail', sa.Column('customer_lat', sa.Float(), nullable=False))
    op.add_column('hail', sa.Column('customer_lon', sa.Float(), nullable=False))
    op.add_column('hail', sa.Column('operateur_id', sa.Integer(), nullable=True))
    op.drop_column('hail', 'client_lat')
    op.drop_column('hail', 'client_lon')
    op.drop_column('hail', 'client_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hail', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hail', sa.Column('client_lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('hail', sa.Column('client_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('hail', 'operateur_id')
    op.drop_column('hail', 'customer_lon')
    op.drop_column('hail', 'customer_lat')
    op.drop_column('hail', 'customer_id')
    op.drop_table('customer')
    ### end Alembic commands ###
