"""Add history fields

Revision ID: 497dacf2e3ba
Revises: 4bf756d958a1
Create Date: 2015-04-01 18:27:23.044611

"""

# revision identifiers, used by Alembic.
revision = '497dacf2e3ba'
down_revision = '4bf756d958a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    enum_via = sa.Enum('form', 'api', name='via')
    impl_via = enum_via.dialect_impl(bind.dialect)
    impl_via.create(bind, checkfirst=True)

    op.add_column('ADS', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('ADS', sa.Column('added_by', sa.Integer(), nullable=True))
    op.add_column('ADS', sa.Column('added_via', enum_via))
    op.add_column('ADS', sa.Column('last_update_at', sa.DateTime(), nullable=True))
    op.add_column('ADS', sa.Column('source', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'ADS', 'user', ['added_by'], ['id'])
    op.add_column('conducteur', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('conducteur', sa.Column('added_by', sa.Integer(), nullable=True))
    op.add_column('conducteur', sa.Column('added_via', enum_via))
    op.add_column('conducteur', sa.Column('last_update_at', sa.DateTime(), nullable=True))
    op.add_column('conducteur', sa.Column('source', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'conducteur', 'user', ['added_by'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conducteur', type_='foreignkey')
    op.drop_column('conducteur', 'source')
    op.drop_column('conducteur', 'last_update_at')
    op.drop_column('conducteur', 'added_via')
    op.drop_column('conducteur', 'added_by')
    op.drop_column('conducteur', 'added_at')
    op.drop_constraint(None, 'ADS', type_='foreignkey')
    op.drop_column('ADS', 'source')
    op.drop_column('ADS', 'last_update_at')
    op.drop_column('ADS', 'added_via')
    op.drop_column('ADS', 'added_by')
    op.drop_column('ADS', 'added_at')
    ### end Alembic commands ###
