"""Add api-key on user

Revision ID: 3e8b56d60090
Revises: 10caa96b2356
Create Date: 2015-04-24 14:41:39.777452

"""

# revision identifiers, used by Alembic.
revision = '3e8b56d60090'
down_revision = '10caa96b2356'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apikey', sa.String(length=36),
        nullable=True))
    conn = op.get_bind()
    result = conn.execute('SELECT id from "user"')
    for r in result.fetchall():
        conn.execute('UPDATE "user" SET apikey=\'{}\' where id={}'.format(
            str(uuid4()), r[0]))
    op.alter_column('user', 'apikey', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apikey')
    ### end Alembic commands ###
