"""Update nullable and unique on ADS

Revision ID: 27df69f29c56
Revises: 4bf756d958a1
Create Date: 2015-04-03 11:56:19.348354

"""

# revision identifiers, used by Alembic.
revision = '27df69f29c56'
down_revision = '4bf756d958a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ADS', 'artisan',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'doublage',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'horodateur',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'marque',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'modele',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'motorisation',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('ADS', 'nom_societe',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'personne',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'pmr',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'relais',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'taximetre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(u'ADS_immatriculation_key', 'ADS', type_='unique')
    op.drop_constraint(u'ADS_numero_key', 'ADS', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'ADS_numero_key', 'ADS', ['numero'])
    op.create_unique_constraint(u'ADS_immatriculation_key', 'ADS', ['immatriculation'])
    op.alter_column('ADS', 'taximetre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'relais',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'pmr',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'personne',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'nom_societe',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'motorisation',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('ADS', 'modele',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'marque',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'horodateur',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'doublage',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'artisan',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
