"""ajout table departement zupc

Revision ID: 4a6b378729be
Revises: 4a8d16efc099
Create Date: 2015-03-26 17:01:04.188179

"""

# revision identifiers, used by Alembic.
revision = '4a6b378729be'
down_revision = '4a8d16efc099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ZUPC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('shape', sa.String(length=10000), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ADS', 'artisan',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'doublage',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'horodateur',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'immatriculation',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('ADS', 'marque',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'modele',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'motorisation',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('ADS', 'nom_societe',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'personne',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ADS', 'pmr',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'relais',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ADS', 'taximetre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conducteur', 'carte_pro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conducteur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conducteur', 'prenom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conducteur', 'prenom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conducteur', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conducteur', 'carte_pro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ADS', 'taximetre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'relais',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'pmr',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'personne',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'nom_societe',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'motorisation',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('ADS', 'modele',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'marque',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'immatriculation',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('ADS', 'horodateur',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ADS', 'doublage',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ADS', 'artisan',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('ZUPC')
    op.drop_table('departement')
    ### end Alembic commands ###
