"""Add ads and conducteurs tables

Revision ID: 4a8d16efc099
Revises: 381ff3809f91
Create Date: 2015-03-25 13:56:20.836798

"""

# revision identifiers, used by Alembic.
revision = '4a8d16efc099'
down_revision = '381ff3809f91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('immatriculation', sa.String(length=80), nullable=True),
    sa.Column('modele', sa.String(length=255), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('motorisation', sa.String(length=80), nullable=True),
    sa.Column('puissance', sa.Float(), nullable=True),
    sa.Column('doublage', sa.Boolean(), nullable=True),
    sa.Column('relais', sa.Boolean(), nullable=True),
    sa.Column('pmr', sa.Boolean(), nullable=True),
    sa.Column('marque', sa.String(length=255), nullable=True),
    sa.Column('horodateur', sa.String(length=255), nullable=True),
    sa.Column('taximetre', sa.String(length=255), nullable=True),
    sa.Column('date_dernier_ct', sa.DateTime(), nullable=True),
    sa.Column('date_validite_ct', sa.DateTime(), nullable=True),
    sa.Column('nom_societe', sa.String(length=255), nullable=True),
    sa.Column('artisan', sa.String(length=255), nullable=True),
    sa.Column('personne', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('immatriculation'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('conducteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.DateTime(), nullable=True),
    sa.Column('carte_pro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conducteurs')
    op.drop_table('ADS')
    ### end Alembic commands ###
