"""Add ZUPC to ADS

Revision ID: 7e8fe7e8e25
Revises: 33fce94e17af
Create Date: 2015-03-27 10:28:57.031834

"""

# revision identifiers, used by Alembic.
revision = '7e8fe7e8e25'
down_revision = '33fce94e17af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ADS', sa.Column('ZUPC', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ADS', 'ZUPC', ['ZUPC'], ['id'])
    op.alter_column('departement', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departement', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'ADS', type_='foreignkey')
    op.drop_column('ADS', 'ZUPC')
    ### end Alembic commands ###
